version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_task2
    environment:
      POSTGRES_DB: securedb
      POSTGRES_USER: erik
      POSTGRES_PASSWORD: erikcoolboy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pinger:
    build: .
    container_name: db_pinger
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/logs
    # логи pinger будут видны через `docker logs db_pinger`

volumes:
  db_data:
