CREATE USER shop_user WITH PASSWORD 'shoppass123';

GRANT CONNECT ON DATABASE shop_db TO shop_user;
GRANT USAGE ON SCHEMA public TO shop_user;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO shop_user;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO shop_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO shop_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO shop_user;
